### ISSUE TITLE
Using with controllerAs syntax

### ISSUE THREAD

**Issue by hainessss** [kensho/ng-describe#23]
Is it possible to test a controller instance that uses controllerAs instead of scope?

Thanks,

**Comment by bahmutov** [comment]
Good question, never tried it (we don't really use this syntax in our angular code). Will look into this.

**Comment by bahmutov** [comment]
Related tutorial on `controllerAs` syntax in angular http://blog.thoughtram.io/angularjs/2015/01/02/exploring-angular-1.3-bindToController.html

**Comment by bahmutov** [comment]
See https://github.com/kensho/ng-describe#test-controlleras-syntax

**Comment by hainessss** [comment]
Thanks so much for the quick answer!  Love this module!
