### ISSUE TITLE
Add shortcut for writing http backend mocks

### ISSUE THREAD

**Issue by bahmutov** [kensho/ng-describe#30]
Something like
```js
http: {
  get: {
    '/foo/bar': 'baz'
  }
}
```

**Comment by josephong** [comment]
Will we be able to supply functions to enable using json spec dependencies? Or an alternative syntax?

**Comment by bahmutov** [comment]
I agree, but I am not sure what is the best syntax. I am thinking maybe even functions with injections or parameters routing

```js
http: {
  get: {
    '/foo/:id': function (id) {
       // return data or promise
       return { hi: id };
    }
}
```

**Comment by bahmutov** [comment]
Added 'GET' support, need to add 'POST'
