### ISSUE TITLE
Beginner to TDD, Karma and ng-describe - unable to get things working

### ISSUE THREAD

**Issue by tomardern** [kensho/ng-describe#39]
Hi,

I must admit I'm a novice to TDD, Karma and ng-describe. I've been battling with ng-describe all afternoon.

After following the installation instructions within the readme, I'm getting errors when running "karma run":
```
 Uncaught TypeError: Cannot read property 'fn' of undefined
  at /node_modules/check-more-types/check-more-types.js:474
```
Any ideas?

**Comment by bahmutov** [comment]
Hi Tom,
Could you provide any more details, please? Cannot seem to recreate this. One hunch is that you might not have the check-types.js library loaded for some reason, but it tries to use `check.fn`

**Comment by bahmutov** [comment]
I think this will be resolved once I make a single bundle see #38

**Comment by bahmutov** [comment]
Tom, can you try again with ng-describe@1.0.0 - there is a bundle now (see install section) that should include all necessary stuff

**Comment by amycheng** [comment]
@tomardern Had this issue a couple of days ago too but updating the `npm` module fixed it.

`npm update ng-describe` didn't *really* update it. I had to delete the folder (`node_modules/ng-describe`) and run `npm install ng-describe`did the trick

**Comment by bahmutov** [comment]
Hmm, weird, I guess `npm update` is not very smart! Thanks for trying this,
