### ISSUE TITLE
deps is an empty object

### ISSUE THREAD

**Issue by rishitank** [kensho/ng-describe#43]
Hi,

While trying to inject a controller using ng-describe, I am unable to retrieve any of the controller's scope variables or anything for that matter since deps is an empty object, even with a very simple controller with only a scope variable. Is there any special setup required to get this to work? Thanks.

**Comment by bahmutov** [comment]
Hi,

Could it be because you are looking at `deps` object outside the unit test callbacks? See https://github.com/kensho/ng-describe#examples
