### ISSUE TITLE
How to mock GET request with Regex of URL ?

### ISSUE THREAD

**Issue by fretman92** [kensho/ng-describe#51]
Hi, 

The official method of [$httpBackend.when](https://docs.angularjs.org/api/ngMock/service/$httpBackend) support Regexp as *url* parameter.

How does ngDescribe permit mocking url via RegExp?

**Comment by bahmutov** [comment]
Hmm, need to think about that one.

**Comment by bahmutov** [comment]
We mock `http` using an object, which can only have string keys. Maybe we could introduce another syntax using an array of pairs
```js
http: {
  get: {
    '/some/url': 42
  }
}
```
would be same as
```js
http: {
  get: [
    '/some/url', 42,
    /full\/regex\/, [500, 'server error']
  ]
}
```

**Comment by fretman92** [comment]
This syntax could work, but won't be very intuitive I think.

As a workaround, I'd use the native $httpbackend for Regex matching :
``` js
ngDescribe({
    name: 'sample $httpBackend',
    modules: ['module.name', ],
    inject: ['$httpBackend', ],
    tests: function (deps) {
        beforeEach(function () {
            deps.$httpBackend.whenGET(/.+GetContacts.*/).respond(function () {
                return [200, [{ "Id": 12, "Name":"Toto"}]];
            });
        });
    }
});

```

**Comment by bahmutov** [comment]
Yup, that is the way. I think you can even combine `http` with this syntax
```js
http: {
  get': {
    '/some/url', 42
  }
},
tests: function (deps) {
  beforeEach(function () {
    deps.$httpBackend.when ...
  })
}
```
