### ISSUE TITLE
Controller methods not accessible in deps

### ISSUE THREAD

**Issue by sularome** [kensho/ng-describe#53]
If i have a controller that has methods defined on it. Those methods won't be available on scope and i don't have a way to get access to them. Here is an example:
```javascript
angular.module('S', [])
  .controller('sample', function ($timeout, $scope) {
    this.someMethod = function () {
    }
  });
ngDescribe({
  name: 'controller methods',
  modules: 'S',
  inject: [],
  controllers: 'sample',
  tests: function (deps) {
    it('has access to test', function () {
      // how do i access here the someMethod function
    });
  }
});
```

This can happen if i use for example ng-controller="as propertyName" or in my case the ui-router is attaching the controller to the scope for me.

**Comment by bahmutov** [comment]
Take a look at controllerAs test example: https://github.com/kensho/ng-describe#test-controlleras-syntax
