### ISSUE TITLE
http - shortcut for specifying mock HTTP responses...

### ISSUE THREAD

**Issue by dkromp** [kensho/ng-describe#67]
tests: function (deps) {
    it('responds', function (done) {
      deps.$http.get('/my/other/url')
        .then(function (response) {
          // response.status = 202
          // response.data = 42
          done();
        });
      http.flush();
    });

Correct http.flush() in the test block to read deps.http.flush()

**Comment by dkromp** [comment]
Please explain what the done() does in this block.

**Comment by bahmutov** [comment]
`done` is an argument injected by the Jasmine or Mocha test framework. It is a function you should call when your async unit test (which this is, because were are making mock http calls). We call it after we get the response.

**Comment by dkromp** [comment]
Thanks -- I overlooked that in the documentation. Here is a great elaboration about it: http://www.htmlgoodies.com/beyond/javascript/stips/using-jasmine-2.0s-new-done-function-to-test-asynchronous-processes.html
