### ISSUE TITLE
Wallaby breaks when logging Elements

### ISSUE THREAD

**Issue by thebuilder** [kensho/ng-describe#89]
I'm using [Wallaby](https://github.com/wallabyjs/public) when developing, which is working fine. However the ES5 shims that gets included in the dist file breaks the logging of some elements by throwing a `Type Error`. This occurs if trying to log out something like an HTML element.

```
it('test element', ()=>{
    console.log(deps.element[0]);
});

//Throws error
    TypeError: Type error
        at node_modules/ng-describe/dist/ng-describe.js:453
        at src/components/input/radio/radio-group.spec.js:118
```

Running the same test inside a normal 'describe' method works fine, and the element is logged to console.

Is ngDescribe doing anything special with HTML elements?

**Comment by bahmutov** [comment]
could you verify this again to see if this is still a problem, I am using almost the latest es5-shim. If this is a problem, I would ask you for a good unit test case for me to recreate the problem

**Comment by bahmutov** [comment]
I have tried Wallaby but could not make it even load Angular correctly, see https://github.com/kensho/ng-describe/tree/master/test/using-wallaby
I am getting 'angular undefined' in service-spec.js line 1 - if you can make this example work, then we can look at fixing the logging
